### ISSUE TITLE
KV initialization

### ISSUE THREAD

**Issue by Maximus169** [cloudflare/miniflare#214]
Is it possible to init KV store with predefined data from CLI?

I want to initialize KV from CLI likes it is implemented in https://github.com/dollarshaveclub/cloudworker
`cloudflare --kv-file [variable=path]`
In this lib I can do it with `.json` file

Does it work for `miniflare`?

**Comment by leader22** [comment]
Have you tried https://miniflare.dev/storage/kv#persistence ?

**Comment by Maximus169** [comment]
Ah, yeap. After some playing with API got how it works. Thanks! 😄 

Btw, maybe, it will be good to have some examples on docs for newbies as me 🤔
