### ISSUE TITLE
Bump undici to 4.15.0

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/miniflare#220]
Miniflare is currently not compatible with @octokit/core. [From Discord](https://discord.com/channels/595317990191398933/891052295410835476/953804749755518976), a bug in [undici ](https://github.com/nodejs/undici/issues/1225) that was [fixed](https://github.com/nodejs/undici/pull/1242). To fix just need to update to undici@4.15.0.

**Comment by f5io** [comment]
this is currently preventing us from using sveltekit with miniflare as [this](https://github.com/sveltejs/kit/pull/4548) was recently added to sveltekit. is there any chance we can get this as a minor patch?
