### ISSUE TITLE
Test helper to await Durable Object's alarms

### ISSUE THREAD

**Issue by robertcepa** [cloudflare/miniflare#322]
We would like to test the side effects in our alarms, but the best way to do it now seems to be sleeping in tests for MAX_ALARM_TIMEOUT (which can slow tests down significantly), or mocking an internal function used in alarm via jest.

Would it be a good idea to expose a similar API to `res.waitUntil()` (e.g., `await res.waitForAlarms()`), which optionally accepts an argument to change the alarm interval, so they can be tested instantly?

**Comment by CraigglesO** [comment]
Hey! I wanted to work on this for myself too.

I've been thinking more along the lines of:
```ts
global.flushDurableObjectAlarms(ids?: DurableObjectId[])
```
Where no ids specified means to call all existing alarms.

I'll try to find time this week to add this.
