### ISSUE TITLE
Vite plugin for development

### ISSUE THREAD

**Issue by DaniFoldi** [cloudflare/miniflare#325]
Many frameworks use vite as their bundler, as it has great HMR support.

Nuxt, being a widely used example has `nuxi dev` which starts up a dev server (on multiple ports which have special purposes).

Currently, Miniflare can watch files and rebuild as required, however it doesn't use a vite-powered dev server. Alternatively, I can use `nuxi dev`, which doesn't have any Workers-specific functionality, such as `HTMLRewriter`, `caches` or any environment bindings.

I'm not sure if making a vite-specific package would be the best solution, however it's possible that unplugin (which is a plugin compatibility layer on top of webpack, esbuild, rollup and vite) supports all required features. Ideally, I'm thinking of a plugin that I can specify to enable "Miniflare mode" (somewhat similar to a jest environment).

A few references:
- Vite Plugin API guide: https://vitejs.dev/guide/api-plugin.html#authoring-a-plugin
- Nuxi dev command: https://v3.nuxtjs.org/api/commands/dev
- Nitro, the server engine used by Nuxt: https://nitro.unjs.io
- Unplugin: https://github.com/unjs/unplugin

I've found this repository posted by @Aslemammad on the Discord server, which I'll include here for reference, I haven't checked the code too much: https://github.com/Aslemammad/vite-plugin-cloudflare

**Comment by Aslemammad** [comment]
Thanks for mentioning vite-plugin-cloudflare!
In the next few days, I'll release a significant breaking change for vite-plugin-cloudflare which has first-class miniflare support without breaking any existing vite app and works along the vite dev server itself (no double servers and conflicts)! and it'd enable bundling your vite apps quickly with the plugin without the current CLI mode!

**Comment by Aslemammad** [comment]
Here's it folks. Vite-plugin-cloudflare was released just now.
Develop, bundle and integrate your vite apps with your Cloudflare workers easily!

- Universal Vite plugin
- Lightning builds
- Fast development and HMR compatible reloads
- Miniflare native support

https://github.com/Aslemammad/vite-plugin-cloudflare

**Comment by litewarp** [comment]
Is there a vite miniflare environment or do you know how to use the jest one with your package?

**Comment by Aslemammad** [comment]
@litewarp Feel free to create an issue in my package and discuss it there!

**Comment by bbhxwl** [comment]
> Here's it folks. Vite-plugin-cloudflare was released just now. Develop, bundle and integrate your vite apps with your Cloudflare workers easily!
> 
> * Universal Vite plugin
> * Lightning builds
> * Fast development and HMR compatible reloads
> * Miniflare native support
> 
> https://github.com/Aslemammad/vite-plugin-cloudflare

How can I use kv in nuxt?
