### ISSUE TITLE
r2 package lists minimum NodeJS version as 16.13 whereas every other component uses 16.7

### ISSUE THREAD

**Issue by vlovich** [cloudflare/miniflare#353]
Every other Miniflare package lists the minimum runtime as 16.7. Is there something about R2 that requires a new version?

Reason I ran into this is that the official NodeJS Arch package only has 16.11.1. To get the others you have to use the community nodejs-lts-gallium package.

**Comment by CraigglesO** [comment]
https://github.com/cloudflare/miniflare/pull/333

https://github.com/cloudflare/miniflare/pull/333#issuecomment-1222296278

For me all packages read 16.13 though, that's strange.

**Comment by vlovich** [comment]
Uggh. I should have been specific. I was running miniflare 2.5.0 not latest.

**Comment by CraigglesO** [comment]
I kept forgetting to suggest this, but is it possible to ignore the issue via [--ignore-engines](https://github.com/gilbarbara/react-joyride/issues/131#issuecomment-253319816)? This seems to be limited to yarn though. The alternative for npm is to make an `.npmrc` with `engine-strict=false`. [I use PNPM and this has worked for me in the past](https://pnpm.io/npmrc#engine-strict).

The other thing that is strange about this is I copy pasted the KV module before working on R2, so it SHOULD be 16.7 for the earlier miniflare version.
