### ISSUE TITLE
🐛 BUG: --experimental-local is not supported with d1

### ISSUE THREAD

**Issue by Zombobot1** [cloudflare/miniflare#479]
### What version of `Wrangler` are you using?

2.4.4

### What operating system are you using?

mac

### Describe the Bug

Execution of ```wrangler dev --experimental-local --persist``` leads to the next error:
service core:user:rub: Uncaught TypeError: Cannot read properties of undefined (reading 'middleware')
  at d1-beta-facade.entry.js:65:31
✘ [ERROR] local worker: MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.

Execution of ```wrangler dev --local --persist``` works fine

**Comment by JustinBeckwith** [comment]
Oof - earlier today I filed both of these as separate issues on wrangler ... maybe I should just be following this issue instead:
- https://github.com/cloudflare/wrangler2/issues/2666
- https://github.com/cloudflare/wrangler2/issues/2667

Right now I'm pretty much stuck for testing locally.

**Comment by admah** [comment]
The PR listed above should implement the fix for this issue. If it persists once the Miniflare version is updated in Wrangler, please reopen.
