### ISSUE TITLE
Update docs for wrangler v3

### ISSUE THREAD

**Issue by Cherry** [cloudflare/miniflare#595]
There's a migration guide from version 2 in the docs, but the getting started guides still include things like this:
`npx miniflare`

which of course does not work with the latest released version.

https://miniflare.dev/get-started/cli

When folks google "run cloudflare workers locally", https://blog.cloudflare.com/miniflare/ is the first result, which leads people to the miniflare docs.

**Comment by idl3** [comment]
A quick win would be to update the blog post in https://blog.cloudflare.com/miniflare/ to include an "Updated information" block that will point them to the latest documentation. So we don't mess up SEO too much but still get things up to date.
