### ISSUE TITLE
Is is it possible to collect coverage with vitest-environment-miniflare?

### ISSUE THREAD

**Issue by sirganya** [cloudflare/miniflare#750]
Currently I end up with 0% coverage over all files.

**Comment by Szebu** [comment]
Yes

**Comment by petebacondarwin** [comment]
We have a new approach to Vitest testing: `@cloudflare/vitest-pool-workers`, which supports basic istanbul based instrumented code coverage. There are issues with getting native coverage working though. See https://github.com/cloudflare/workers-sdk/issues/5266
Closing this issue as future work with be focussed on improving the new approach.
