### ISSUE TITLE
@miniflare/shared should not depend on @types/better-sqlite3

### ISSUE THREAD

**Issue by FlatMapIO** [cloudflare/miniflare#762]
Although I've already included `vitest-environment-miniflare/globals` in types:
```
"types": [
  "@cloudflare/workers-types/2023-07-01",
  "vitest-environment-miniflare/globals"
]

```
But in vscode, the worker api still points to @types/node #761.

I looked up the following dependency via pnpm why @types/node.

```
vitest-environment-miniflare 2.14.2
├─┬ @miniflare/queues 2.14.2
│ └─┬ @miniflare/shared 2.14.2
│   └─┬ @types/better-sqlite3 7.6.9
│     └── @types/node 20.11.17
```

I think we should avoid introducing it to prevent type problems.

**Comment by penalosa** [comment]
It looks like you're using the deprecated Miniflare v2. [Miniflare 3's new Vitest integration should avoid this issue](https://blog.cloudflare.com/workers-vitest-integration)—could you give that a try?
