### ISSUE TITLE
Type incompatibility issue between miniflare and workers-types

### ISSUE THREAD

**Issue by alokmenghrajani** [cloudflare/miniflare#766]
It seems that D1Database from this package isn't compatible with the one from @cloudflare/workers-types (which pulls the type information from @miniflare/workerd). As a result, when creating a database in a test, I have to cast to `unknown` and then workers-types' `D1Database` (see https://github.com/zxsdotch/d1-batch/blob/acd1b390a15a5f658950ec8581eccab4349fc66f/batch.test.ts#L27 for an example).

The error I get from TypeScript is:
```
Type 'import("..../d1-batch/node_modules/@miniflare/d1/dist/src/index").D1Database' is not assignable to type 'D1Database'.
  The types returned by 'prepare(...).run()' are incompatible between these types.
    Type 'Promise<import("..../d1-batch/node_modules/@miniflare/d1/dist/src/index").D1Result<T>>' is not assignable to type 'Promise<D1Result<T>>'.
      Type 'import("..../d1-batch/node_modules/@miniflare/d1/dist/src/index").D1Result<T>' is not assignable to type 'D1Result<T>'.
        Type 'D1Result<T>' is not assignable to type 'D1Response'.
          Types of property 'success' are incompatible.
            Type 'boolean' is not assignable to type 'true'.ts(2322)
```

It's possible that @miniflare/workerd is incorrect (see https://github.com/cloudflare/workerd/issues/940).

**Comment by petebacondarwin** [comment]
I propose that you try updating to use Miniflare 3. The types that you are referring to above (i.e. from `@miniflare/d1`) are for the old Miniflare 2 library that is not necessarily compatible with the actual types for production deployments.

**Comment by alokmenghrajani** [comment]
I think this issue goes away with miniflare 3 since there's no more any direct method that returns a `D1Database` (i.e. `new MiniflareD1Database` no longer exists)? The `env` from `cloudflare:test` is initially an empty interface and additional types are supplied by the user, so those will always match.

**Comment by alokmenghrajani** [comment]
Yes, this is good for me. Thanks!
