### ISSUE TITLE
How to use Worker's new native RPC feature? 

### ISSUE THREAD

**Issue by amiranvarov** [cloudflare/miniflare#771]
Hey, CF Workers recently introduced great feature RPC [Docs](https://developers.cloudflare.com/workers/runtime-apis/rpc/). 

I was wondering how to set up integration testing using Miniflare, but couldn't find any information in docs. Can anyone please explain maybe here or add them in the docs?

**Comment by petebacondarwin** [comment]
We recommend that you use the new Vitest integration for workerd for integration testing RPC in Workers.
Here is a recipe for how it can be done: https://github.com/cloudflare/workers-sdk/tree/main/fixtures/vitest-pool-workers-examples/rpc

**Comment by petebacondarwin** [comment]
And here is more documentation about this integration: https://developers.cloudflare.com/workers/testing/vitest-integration/

**Comment by amiranvarov** [comment]
Thank you very much @petebacondarwin !!! 🍻
