### ISSUE TITLE
Console for D1

### ISSUE THREAD

**Issue by JoyceBabu** [cloudflare/miniflare#777]
Does Miniflare D1 include a console for running SQL queries directly?

**Comment by edmundhung** [comment]
Hi @JoyceBabu 

No, Miniflare itself doesn't include a console for running SQL queries directly. However, you can access a SQL console on the D1 SQL Database page inside the Cloudflare dashboard.

If you have any future questions, I recommend checking out the [workers-sdk repository](https://github.com/cloudflare/workers-sdk), as this repository is focused on Miniflare v2, which is only receiving critical security updates.

Thanks!

**Comment by JoyceBabu** [comment]
Thank you. I managed to solve the issue by querying the SQLite file directly.
