### ISSUE TITLE
`envPath` param in MiniflareOptions does not exist

### ISSUE THREAD

**Issue by KyGuy2002** [cloudflare/miniflare#790]
In various parts of the docs including the D1 page it references an `envPath` option:
![image](https://github.com/user-attachments/assets/28b714b2-df48-43e5-8ff7-ce582cd4dcd6)

Intellisense is not recognizing this option.  I see mention of it in the 2.0.0 changelog, but I am on the latest 3.20241205.0 and it seems to be gone.

Is this just an issue with the docs, and this option is no longer needed?

Just wanted to bring this up as it is causing some confusion.
Sorry if I am misunderstanding the note.  Thanks!

**Comment by CarmenPopoviciu** [comment]
hi @KyGuy2002,

`envPath` is no longer supported in [Miniflare 3](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare), though it used to be supported in [Miniflare 2](https://github.com/cloudflare/miniflare), so what you're seeing is def a docs thing. Can you please point me at which docs you are looking specifically, just to make sure we're looking at the same thing?

🙏

**Comment by emily-shen** [comment]
Hiya, thanks so much for flagging this! We've moved the miniflare docs to the main cloudflare docs now to reduce confusion, and updated it a bit including removing references to `envPath`. You can find those here https://developers.cloudflare.com/workers/testing/miniflare/ (miniflare.dev should also redirect). Thanks again :))
